name: Test no_std
on:
  push:
    paths:
      - "**/*.rs"
jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install no_std stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: thumbv6m-none-eabi
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --target thumbv6m-none-eabi
